#!/usr/bin/env bash
# 0-change_your_home_IP

# Backup the original hosts file
cp /etc/hosts /etc/hosts.bak

# Remove any previous entries for localhost and facebook.com to avoid duplicates
sed -i '/localhost/d' /etc/hosts
sed -i '/facebook.com/d' /etc/hosts

# Add new entries
echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
